const productos = {
    pulseras: [
        { id: "pulsera001", nombre: "Pulsera Dorada 01", precio: "$199", img: "media/img/pulseras/pulseraChapeadaOjitos.jpg" },
        { id: "pulsera002", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaBonita.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: ["media/img/pulseras/pulseraDoradaCerecitas.jpg","media/img/pulseras/pulseraDoradaCerecitas2.jpg"] },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaChunkyLinda.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaCorazonBolitas.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: ["media/img/pulseras/pulseraDoradaEsla.jpg", "media/img/pulseras/pulseraDoradaEsla2.jpg"] },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaLayers.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaLinda.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaLindi.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaLisa.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaPeny.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaSencilla.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaTorcidita.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaTria.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaVibra.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraExteindete.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: ["media/img/pulseras/pulseraPlateadaConchas.jpg","media/img/pulseras/pulseraPlateadaConchas2.jpg"] },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraPlateadaEsla.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraPlateadaLibra.jpg" },
        { id: "pulsera003", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulserasDoaradas.jpg" },
    ],
    cadenas: [
        { id: "cadena001", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInox.jpg" },
        { id: "cadena002", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxBicolorDije.jpg" },
        { id: "cadena003", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxBolitas.jpg" },
        { id: "cadena004", nombre: "Cadena Acero 55cm", precio: "$249", img: ["media/img/cadenas/cadenaAceroInoxCorazon.jpg","media/img/cadenas/cadenaAceroInoxCorazon2.jpg"] },
        { id: "cadena005", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxCorazonChunky.jpg" },
        { id: "cadena006", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxCorazones.jpg" },
        { id: "cadena007", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxCorazonMini.jpg" },
        { id: "cadena008", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDijeLetra.jpg" },
        { id: "cadena009", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDijeLetraLisa.jpg" },
        { id: "cadena010", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDijeLunaMini.jpg" },
        { id: "cadena011", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDijeMarcaLetra.jpg" },
        { id: "cadena012", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDijeMini.jpg" },
        { id: "cadena013", nombre: "Cadena Acero 55cm", precio: "$249", img: ["media/img/cadenas/cadenaAceroInoxDoradaDijeChunky.jpg","media/img/cadenas/cadenaAceroInoxDoradaDijeChunky2.jpg"] },
        { id: "cadena014", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDoradaDijeCuadrado.jpg" },
        { id: "cadena015", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDoradaDijeLuna.jpg" },
        { id: "cadena016", nombre: "Cadena Acero 55cm", precio: "$249", img: ["media/img/cadenas/cadenaAceroInoxDoradaLetraConFondo.jpg","media/img/cadenas/cadenaAceroInoxDoradaLetraConFondo2.jpg"] },
        { id: "cadena017", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDosCorazones.jpg" },
        { id: "cadena018", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxLetra.jpg" },
        { id: "cadena019", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxLetra2.jpg" },
        { id: "cadena020", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxLetraLisa.jpg" },
        { id: "cadena021", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxLetraRellena.jpg" },
        { id: "cadena022", nombre: "Cadena Acero 55cm", precio: "$249", img: ["media/img/cadenas/cadenaAceroInoxPlateadaDijeChonky.jpg","media/img/cadenas/cadenaAceroInoxPlateadaDijeChonky2.jpg"] },
        { id: "cadena023", nombre: "Cadena Acero 55cm", precio: "$249", img: "" },
    ],
    layers: [
        { id: "layers001", nombre: "Layer Gold", precio: "$199", img: "media/img/layers/aceroInoxLayerBolitas.jpg" },
        { id: "layers002", nombre: "Layer Gold", precio: "$199", img: "media/img/layers/aceroInoxLayerCorazonV.jpg" },
        { id: "layers003", nombre: "Layer Gold", precio: "$199", img: "media/img/layers/aceroInoxLayersLisos.jpg" },
        { id: "layers004", nombre: "Layer Gold", precio: "$199", img: "media/img/layers/aceroInoxLayersMar.jpg" },
        ],
    aretes: [
        { id: "arete001", nombre: "Arete Dorado Largo", precio: "$199",img: ["media/img/aretes/areteDoradoLargo.jpg","media/img/aretes/areteDoradoLargo2.jpg","media/img/aretes/areteDoradoLargo3.JPG"],
            nuevo: false
        },
        { id: "arete002", nombre: "Arracada Chunky Plata", precio: "$199",img: "media/img/aretes/areteArracadaChunkyPlata.jpg",
            nuevo: false
        },
        { id: "arete003", nombre: "Huggie Dorada", precio: "$199",img: ["media/img/aretes/areteArracadaHuggieDorada.jpg","media/img/aretes/areteArracadaHuggieDorada2.jpg"],
            nuevo: false
        },
        { id: "arete004", nombre: "Arracada Premium Dorada", precio: "$199",img: ["media/img/aretes/areteArradaPremiumDorada1.jpg","media/img/aretes/areteArradaPremiumDorada2.jpg"],
            nuevo: false
        },
        { id: "arete005", nombre: "Gota Plata", precio: "$199",img: "media/img/aretes/areteGotaPlata.jpg",
            nuevo: false
        },
        { id: "arete006", nombre: "Huggie con Circonia", precio: "$199",img: ["media/img/aretes/areteHuggieDoradoCirconia.jpg","media/img/aretes/areteHuggieDoradoCirconia2.jpg"],
            nuevo: true
        },
        { id: "arete007", nombre: "Huggie Dorada Lindi", precio: "$199",img: "media/img/aretes/areteHuggiesDorado.jpg",
            nuevo: true
        },
        { id: "arete008", nombre: "Arete BOLA", precio: "$199",img: "media/img/aretes/Photoroom_20251208_201819.jpg",
            nuevo: false
        },
        { id: "arete009", nombre: "Roberta Dorada", precio: "199", img: "media/img/aretes/Photoroom_20251208_201859.jpg" },
        { id: "arete010", nombre: "Arete BOLA", precio: "199", img: "media/img/aretes/Photoroom_20251208_201932.jpg" },
        { id: "arete011", nombre: "Arete BOLA", precio: "199", img: "media/img/aretes/Photoroom_20251208_201959.jpg" },
        { id: "arete012", nombre: "Arete BOLA", precio: "199", img: "media/img/aretes/Photoroom_20251208_202106.jpg" },
        { id: "arete013", nombre: "Arete BOLA", precio: "199", img: "media/img/aretes/Photoroom_20251208_202304.jpg" },
        { id: "arete014", nombre: "Arete BOLA", precio: "199", img: "media/img/aretes/Photoroom_20251208_202334.jpg" },
        { id: "arete015", nombre: "Arete BOLA", precio: "199", img: "media/img/aretes/Photoroom_20251208_202353.jpg" },
        { id: "arete016", nombre: "Arete BOLA", precio: "199", img: "media/img/aretes/Photoroom_20251208_202421.jpg" },
        { id: "arete017", nombre: "Arete BOLA", precio: "199", img: "media/img/aretes/Photoroom_20251208_202455.jpg" },
        { id: "arete018", nombre: "Arete BOLA", precio: "199", img: "media/img/aretes/Photoroom_20251208_202531.jpg" },
        { id: "arete019", nombre: "Arete BOLA", precio: "199", img: "media/img/aretes/Photoroom_20251208_203132.jpg" }
    ],
    anillos: [
        { id: "anillo001", nombre: "3 Rojos", precio: "$199", img: "media/img/anillos/anillo3rojos.jpg" },
        { id: "anillo002", nombre: "Divina", precio: "$199", img: "media/img/anillos/anilloAbstracto.jpg" },
        { id: "anillo003", nombre: "Amor Dorado", precio: "$199", img: "media/img/anillos/anilloAmorDorado.jpg" },
        { id: "anillo004", nombre: "Apapachate", precio: "$199", img: "media/img/anillos/anilloApapachate.jpg" },
        { id: "anillo005", nombre: "Amuleto de Encanto", precio: "$199", img: "media/img/anillos/anilloBrillas.jpg" },
        { id: "anillo006", nombre: "El Cora Dorado", precio: "$199", img: "media/img/anillos/anilloCoraDorado.jpg" },
        { id: "anillo007", nombre: "Anillo Crois", precio: "$199", img: "media/img/anillos/anilloCroisPlata.jpg" },
        { id: "anillo008", nombre: "Anillo Dorado", precio: "$199", img: "media/img/anillos/anilloDorado.jpg" },
        { id: "anillo009", nombre: "Estrella Dorada", precio: "$199", img: "media/img/anillos/anilloEstrella.jpg" },
        { id: "anillo010", nombre: "Lazo Bicolor", precio: "$199", img: "media/img/anillos/anilloLazoBicolor.jpg" },
        { id: "anillo011", nombre: "Corazon Dorado", precio: "$199", img: "media/img/anillos/anilloLazoCorazonDorado.jpg" },
        { id: "anillo012", nombre: "Trio Bi", precio: "$199", img: "media/img/anillos/anilloTrioBi.jpg" },
        { id: "anillo013", nombre: "Trio Dorado", precio: "$199", img: "media/img/anillos/anilloTrioDorado.jpg" },
        { id: "anillo014", nombre: "Union Dorada", precio: "$199", img: "media/img/anillos/anilloUnionDorada.jpg" },
        { id: "anillo015", nombre: "El Dorado", precio: "$199", img: "media/img/anillos/elDorado.jpg" },
        { id: "anillo016", nombre: "Gypto Gold", precio: "$199", img: "media/img/anillos/gyptoDorado.jpg" },
        { id: "anillo017", nombre: "Golden Piece", precio: "$199", img: "media/img/anillos/impalaDorado.jpg" },
        
    ],
    piercings: [
        { id: "piercing001", nombre: "Piercing Acero", precio: "$199", img: "" }
    ],
    relojes: [
        { id: "reloj001", nombre: "Reloj Pleateado", precio: "$199", img: ["media/img/relojs/relojPlateado.jpg","media/img/relojs/relojPlateado2.jpg","media/img/relojs/relojPlateado3.jpg"] }
    ]
};