const products = {
    pulseras: [
        { id: "pulsera001", nombre: "Pulsera Dorada 01", precio: "$199", img: "media/img/pulseras/pulseraChapeadaOjitos.jpg" },
        { id: "pulsera002", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaBonita.jpg" },
        { id: "pulsera004", nombre: "Pulsera Inox Plata", precio: "$159", img: ["media/img/pulseras/pulseraDoradaCerecitas.jpg","media/img/pulseras/pulseraDoradaCerecitas2.jpg"] },
        { id: "pulsera005", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaChunkyLinda.jpg" },
        { id: "pulsera006", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaCorazonBolitas.jpg" },
        { id: "pulsera007", nombre: "Pulsera Inox Plata", precio: "$159", img: ["media/img/pulseras/pulseraDoradaEsla.jpg", "media/img/pulseras/pulseraDoradaEsla2.jpg"] },
        { id: "pulsera008", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaLayers.jpg" },
        { id: "pulsera009", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaLinda.jpg" },
        { id: "pulsera0010", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaLindi.jpg" },
        { id: "pulsera0011", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaLisa.jpg" },
        { id: "pulsera0012", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaPeny.jpg" },
        { id: "pulsera0013", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaSencilla.jpg" },
        { id: "pulsera0014", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaTorcidita.jpg" },
        { id: "pulsera0015", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaTria.jpg" },
        { id: "pulsera0016", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraDoradaVibra.jpg" },
        { id: "pulsera0017", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraExteindete.jpg" },
        { id: "pulsera0018", nombre: "Pulsera Inox Plata", precio: "$159", img: ["media/img/pulseras/pulseraPlateadaConchas.jpg","media/img/pulseras/pulseraPlateadaConchas2.jpg"] },
        { id: "pulsera0019", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraPlateadaEsla.jpg" },
        { id: "pulsera0020", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulseraPlateadaLibra.jpg" },
        { id: "pulsera0021", nombre: "Pulsera Inox Plata", precio: "$159", img: "media/img/pulseras/pulserasDoaradas.jpg" },
    ],
    cadenas: [
        { id: "cadena001", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInox.jpg" },
        { id: "cadena002", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxBicolorDije.jpg" },
        { id: "cadena003", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxBolitas.jpg" },
        { id: "cadena004", nombre: "Cadena Acero 55cm", precio: "$249", img: ["media/img/cadenas/cadenaAceroInoxCorazon.jpg","media/img/cadenas/cadenaAceroInoxCorazon2.jpg"] },
        { id: "cadena005", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxCorazonChunky.jpg" },
        { id: "cadena006", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxCorazones.jpg" },
        { id: "cadena007", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxCorazonMini.jpg" },
        { id: "cadena008", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDijeLetra.jpg" },
        { id: "cadena009", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDijeLetraLisa.jpg" },
        { id: "cadena010", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDijeLunaMini.jpg" },
        { id: "cadena011", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDijeMarcaLetra.jpg" },
        { id: "cadena012", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDijeMini.jpg" },
        { id: "cadena013", nombre: "Cadena Acero 55cm", precio: "$249", img: ["media/img/cadenas/cadenaAceroInoxDoradaDijeChunky.jpg","media/img/cadenas/cadenaAceroInoxDoradaDijeChunky2.jpg"] },
        { id: "cadena014", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDoradaDijeCuadrado.jpg" },
        { id: "cadena015", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDoradaDijeLuna.jpg" },
        { id: "cadena016", nombre: "Cadena Acero 55cm", precio: "$249", img: ["media/img/cadenas/cadenaAceroInoxDoradaLetraConFondo.jpg","media/img/cadenas/cadenaAceroInoxDoradaLetraConFondo2.jpg"] },
        { id: "cadena017", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxDosCorazones.jpg" },
        { id: "cadena018", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxLetra.jpg" },
        { id: "cadena019", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxLetra2.jpg" },
        { id: "cadena020", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxLetraLisa.jpg" },
        { id: "cadena021", nombre: "Cadena Acero 55cm", precio: "$249", img: "media/img/cadenas/cadenaAceroInoxLetraRellena.jpg" },
        { id: "cadena022", nombre: "Cadena Acero 55cm", precio: "$249", img: ["media/img/cadenas/cadenaAceroInoxPlateadaDijeChonky.jpg","media/img/cadenas/cadenaAceroInoxPlateadaDijeChonky2.jpg"] }
    ],
    layers: [
        { id: "layers001", nombre: "Layer Gold", precio: "$199", img: "media/img/layers/aceroInoxLayerBolitas.jpg" },
        { id: "layers002", nombre: "Layer Gold", precio: "$199", img: "media/img/layers/aceroInoxLayerCorazonV.jpg" },
        { id: "layers003", nombre: "Layer Gold", precio: "$199", img: "media/img/layers/aceroInoxLayersLisos.jpg" },
        { id: "layers004", nombre: "Layer Gold", precio: "$199", img: "media/img/layers/aceroInoxLayersMar.jpg" },
        ],
    aretes: [
        { id: "arete001", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Angelinas.jpg" },
        { id: "arete002", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Flor.jpg" },
        { id: "arete003", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Globo quadro.jpg" },
        { id: "arete004", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_0272.jpg" },
        { id: "arete005", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_0521.jpg" },
        { id: "arete006", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_3111.jpg" },
        { id: "arete007", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_3118.jpg" },
        { id: "arete008", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_3120.jpg" },
        { id: "arete009", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_6874.jpg" },
        { id: "arete010", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_7180.jpg" },
        { id: "arete011", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_7848.jpg" },
        { id: "arete012", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_7849.jpg" },
        { id: "arete013", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_7850.jpg" },
        { id: "arete014", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_8113.jpg" },
        { id: "arete015", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_8119.jpg" },
        { id: "arete016", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_8141.jpg" },
        { id: "arete017", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_8201.jpg" },
        { id: "arete018", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_8202.jpg" },
        { id: "arete019", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_8204.jpg" },
        { id: "arete020", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_8852.jpg" },
        { id: "arete021", nombre: "aretes acero inox", precio: "199", img: ["media/img/aretes/IMG_9146.jpg","media/img/aretes/IMG_9146(1).jpg"] },
        { id: "arete022", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_9152.jpg" },
        { id: "arete023", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_9154.jpg" },
        { id: "arete024", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_9159.jpg" },
        { id: "arete025", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_9170.jpg" },
        { id: "arete026", nombre: "aretes acero inox", precio: "199", img: ["media/img/aretes/IMG_9181.jpg","media/img/aretes/IMG_9181(1).jpg"] },
        { id: "arete027", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/IMG_9184.jpg" },
        { id: "arete028", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Oval.jpg" },
        { id: "arete029", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251208_201819.jpg" },
        { id: "arete030", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251208_201932.jpg" },
        { id: "arete031", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251208_202334.jpg" },
        { id: "arete032", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251208_202353.jpg" },
        { id: "arete033", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251208_202421.jpg" },
        { id: "arete034", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251208_202455.jpg" },
        { id: "arete035", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251208_202531.jpg" },
        { id: "arete036", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251208_203132.jpg" },
        { id: "arete037", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251209_011230.jpg" },
        { id: "arete038", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251209_011639.jpg" },
        { id: "arete039", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251209_012109.jpg" },
        { id: "arete040", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251209_013247.jpg" },
        { id: "arete041", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251209_014349.jpg" },
        { id: "arete042", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251209_014513.jpg" },
        { id: "arete043", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Photoroom_20251209_015637.jpg" },
        { id: "arete044", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Roberta.jpg" },
        { id: "arete045", nombre: "aretes acero inox", precio: "199", img: "media/img/aretes/Triangle.jpg" }
    ],
    anillos: [
        { id: "anillo001", nombre: "3 Rojos", precio: "$199", img: "media/img/anillos/anillo3rojos.jpg" },
        { id: "anillo002", nombre: "Divina", precio: "$199", img: "media/img/anillos/anilloAbstracto.jpg" },
        { id: "anillo003", nombre: "Amor Dorado", precio: "$199", img: "media/img/anillos/anilloAmorDorado.jpg" },
        { id: "anillo004", nombre: "Apapachate", precio: "$199", img: "media/img/anillos/anilloApapachate.jpg" },
        { id: "anillo005", nombre: "Amuleto de Encanto", precio: "$199", img: "media/img/anillos/anilloBrillas.jpg" },
        { id: "anillo006", nombre: "El Cora Dorado", precio: "$199", img: "media/img/anillos/anilloCoraDorado.jpg" },
        { id: "anillo007", nombre: "Anillo Crois", precio: "$199", img: "media/img/anillos/anilloCroisPlata.jpg" },
        { id: "anillo008", nombre: "Anillo Dorado", precio: "$199", img: "media/img/anillos/anilloDorado.jpg" },
        { id: "anillo009", nombre: "Estrella Dorada", precio: "$199", img: "media/img/anillos/anilloEstrella.jpg" },
        { id: "anillo010", nombre: "Lazo Bicolor", precio: "$199", img: "media/img/anillos/anilloLazoBicolor.jpg" },
        { id: "anillo011", nombre: "Corazon Dorado", precio: "$199", img: "media/img/anillos/anilloLazoCorazonDorado.jpg" },
        { id: "anillo012", nombre: "Trio Bi", precio: "$199", img: "media/img/anillos/anilloTrioBi.jpg" },
        { id: "anillo013", nombre: "Trio Dorado", precio: "$199", img: "media/img/anillos/anilloTrioDorado.jpg" },
        { id: "anillo014", nombre: "Union Dorada", precio: "$199", img: "media/img/anillos/anilloUnionDorada.jpg" },
        { id: "anillo015", nombre: "El Dorado", precio: "$199", img: "media/img/anillos/elDorado.jpg" },
        { id: "anillo016", nombre: "Gypto Gold", precio: "$199", img: "media/img/anillos/gyptoDorado.jpg" },
        { id: "anillo017", nombre: "Golden Piece", precio: "$199", img: "media/img/anillos/impalaDorado.jpg" },
        
    ],
    piercings: [
        { id: "piercing001", nombre: "Piercing Acero", precio: "$199", img: "" }
    ],
    relojes: [
        { id: "reloj001", nombre: "Reloj Pleateado", precio: "$199", img: ["media/img/relojs/relojPlateado.jpg","media/img/relojs/relojPlateado2.jpg","media/img/relojs/relojPlateado3.jpg"] }
    ]
};
